Repository googleapis/python-bigquery, pull requests merged in 2020-02, with the labels that each got.

#1 chore: add split repo templates
  .coveragerc
  .flake8
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-please.yml
  .gitignore
  .kokoro/build.sh
  .kokoro/continuous/common.cfg
  .kokoro/continuous/continuous.cfg
  .kokoro/docs/common.cfg
  .kokoro/docs/docs.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/trampoline.sh
  .repo-metadata.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  MANIFEST.in
  docs/conf.py
  docs/snippets.py
  noxfile.py
  renovate.json
  setup.cfg
  setup.py
  synth.metadata
  synth.py
  test_utils/credentials.json.enc
  test_utils/scripts/circleci/get_tagged_package.py
  test_utils/scripts/circleci/twine_upload.sh
  test_utils/scripts/get_target_packages.py
  test_utils/scripts/get_target_packages_kokoro.py
  test_utils/scripts/run_emulator.py
  test_utils/scripts/update_docs.sh
  test_utils/setup.py
  test_utils/test_utils/__init__.py
  test_utils/test_utils/imports.py
  test_utils/test_utils/retry.py
  test_utils/test_utils/system.py
  test_utils/test_utils/vpcsc_config.py
Labels: cla: yes, type: process

#30 refactor: noxfile exclusion from synth changes
  synth.py
Labels: cla: yes, type: cleanup

#35 docs: add limitation note for loading REPEATED fields
  google/cloud/bigquery/client.py
Labels: cla: yes, type: docs

#37 fix: allow partial streaming_buffer statistics
  google/cloud/bigquery/table.py
  tests/unit/test_table.py
Labels: cla: yes

#36 feat: add BigQuery storage client support to DB API
  google/cloud/bigquery/dbapi/_helpers.py
  google/cloud/bigquery/dbapi/connection.py
  google/cloud/bigquery/dbapi/cursor.py
  noxfile.py
  tests/system.py
  tests/unit/test_dbapi__helpers.py
  tests/unit/test_dbapi_connection.py
  tests/unit/test_dbapi_cursor.py
Labels: cla: yes, type: feature request
