Repository googleapis/python-bigquery, pull requests merged in 2020-08, with the labels that each got.

#146 feat: add support and tests for struct fields
  google/cloud/bigquery/_pandas_helpers.py
  setup.py
  tests/system.py
  tests/unit/test_client.py
Labels: automerge, cla: yes

#207 testing: split system tests
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/presubmit/presubmit.cfg
  .kokoro/presubmit/system-2.7.cfg
  .kokoro/presubmit/system-3.8.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  google/cloud/bigquery_v2/proto/encryption_config_pb2.py
  google/cloud/bigquery_v2/proto/model_pb2.py
  google/cloud/bigquery_v2/proto/model_reference_pb2.py
  google/cloud/bigquery_v2/proto/standard_sql_pb2.py
  noxfile.py
  synth.metadata
  synth.py
Labels: cla: yes

#218 chore: fix docs build broken by Sphinx 3.2.0
  google/cloud/bigquery/query.py
Labels: cla: yes

#216 feat(bigquery): add client_options to base class
  google/cloud/bigquery/client.py
  setup.py
Labels: cla: yes

#209 fix: converting to dataframe with out of bounds timestamps
  google/cloud/bigquery/table.py
  setup.py
  tests/unit/test_table.py
Labels: automerge, cla: yes

#230 fix: tweak pyarrow extra to soothe PyPI
  setup.py
Labels: cla: yes

#235 fix: rationalize platform constraints for 'pyarrow' extra
  setup.py
Labels: cla: yes

#241 fix: fix dependency issue in fastavro
  noxfile.py
Labels: cla: yes

#239 feat: add instrumentation to list methods
  google/cloud/bigquery/client.py
  tests/unit/test_client.py
Labels: api: bigquery, cla: yes

#247 chore: use specific version for black
  noxfile.py
Labels: cla: yes

#250 chore: bump pyarrow to 1.0.0
  setup.py
Labels: api: bigquery, cla: yes
