Repository googleapis/python-bigquery, pull requests merged in 2020-04, with the labels that each got.

#76 docs: fix generation warnings in new Sphinx version
  docs/conf.py
  docs/gapic/v2/types.rst
Labels: cla: yes, type: docs

#79 chore: restrict llvmlite version for Python 2.7/3.5 compatibility
  setup.py
Labels: cla: yes, type: process

#80 chore: Migrate python-bigquery synth.py from artman to bazel
  synth.py
Labels: cla: yes, type: process

#87 chore: assure bqstorage extra installs grpcio
  setup.py
Labels: cla: yes, type: process

#46 test: drop per-language version coverage levels
  noxfile.py
Labels: api: bigquery, cla: yes, testing, type: process

#89 chore: remove local test_utils directory
  noxfile.py
  test_utils/credentials.json.enc
  test_utils/scripts/circleci/get_tagged_package.py
  test_utils/scripts/circleci/twine_upload.sh
  test_utils/scripts/get_target_packages.py
  test_utils/scripts/get_target_packages_kokoro.py
  test_utils/scripts/run_emulator.py
  test_utils/scripts/update_docs.sh
  test_utils/setup.py
  test_utils/test_utils/__init__.py
  test_utils/test_utils/imports.py
  test_utils/test_utils/retry.py
  test_utils/test_utils/system.py
  test_utils/test_utils/vpcsc_config.py
Labels: cla: yes, type: cleanup
