Repository googleapis/python-bigquery, pull requests merged in 2020-03, with the labels that each got.

#51 chore(bigquery): bump pyarrow version to 0.16.0
  setup.py
Labels: cla: yes

#47 chore: declare full Python 3.8 support
  noxfile.py
  setup.py
Labels: cla: yes, type: process

#27 fix(bigquery): fix start index with page size for list rows
  google/cloud/bigquery/table.py
  tests/unit/test_client.py
Labels: cla: yes

#52 docs: use timeout in create dataset sample
  samples/create_dataset.py
Labels: cla: yes, type: docs

#43 fix: distinguish server timeouts from transport timeouts
  google/cloud/bigquery/client.py
  google/cloud/bigquery/job.py
  tests/unit/test_client.py
  tests/unit/test_job.py
Labels: api: bigquery, cla: yes

#48 chore: deprecate pandas code paths that don't use pyarrow
  google/cloud/bigquery/__init__.py
  google/cloud/bigquery/client.py
  google/cloud/bigquery/exceptions.py
  google/cloud/bigquery/table.py
  tests/unit/test_client.py
  tests/unit/test_table.py
Labels: cla: yes, type: process

#69 chore: temporarily adjust failing system test
  tests/system.py
Labels: cla: yes, testing, type: process

#64 docs: include details of inherited class members
  docs/conf.py
  google/cloud/bigquery/job.py
Labels: cla: yes, type: docs

#58 fix: improve cell magic error message on missing query
  google/cloud/bigquery/magics.py
  tests/unit/test_magics.py
Labels: cla: yes

#32 feat(bigquery): add create job method
  google/cloud/bigquery/client.py
  tests/unit/test_client.py
Labels: cla: yes

#66 fix(bigquery): fix repr of model reference
  google/cloud/bigquery/model.py
  tests/unit/model/test_model.py
  tests/unit/model/test_model_reference.py
Labels: cla: yes
