Repository googleapis/python-bigquery, pull requests merged in 2020-07, with the labels that each got.

#145 chore: update protobuf version
  .coveragerc
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  CONTRIBUTING.rst
  MANIFEST.in
  docs/_static/custom.css
  docs/_templates/layout.html
  docs/conf.py
  google/cloud/bigquery_v2/gapic/enums.py
  google/cloud/bigquery_v2/proto/encryption_config_pb2.py
  google/cloud/bigquery_v2/proto/encryption_config_pb2_grpc.py
  google/cloud/bigquery_v2/proto/model_pb2.py
  google/cloud/bigquery_v2/proto/model_pb2_grpc.py
  google/cloud/bigquery_v2/proto/model_reference_pb2.py
  google/cloud/bigquery_v2/proto/model_reference_pb2_grpc.py
  google/cloud/bigquery_v2/proto/standard_sql_pb2.py
  google/cloud/bigquery_v2/proto/standard_sql_pb2_grpc.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  setup.cfg
  synth.metadata
  synth.py
  testing/.gitignore
Labels: automerge, cla: yes, context: full

#162 feat(bigquery): add __eq__ method for class PartitionRange and RangePartitioning
  google/cloud/bigquery/table.py
  tests/unit/test_table.py
Labels: cla: yes

#164 chore(deps): remove redundant dependencies
  setup.py
Labels: cla: yes

#170 fix: omit `NaN` values when uploading from `insert_rows_from_dataframe`
  google/cloud/bigquery/_pandas_helpers.py
  google/cloud/bigquery/client.py
  tests/system.py
  tests/unit/test_client.py
Labels: cla: yes

#171 docs(bigquery): add docstring for conflict exception
  google/cloud/bigquery/client.py
Labels: cla: yes

#181 fix: RowIterator.to_arrow() error when BQ Storage client cannot be created
  CHANGELOG.md
  google/cloud/bigquery/table.py
  tests/unit/test_table.py
Labels: cla: yes

#189 chore(packaging): prep for grmp-1.0.0 release
  setup.py
Labels: cla: yes, type: process

#192 test: adjust assertions about pyarrow column values
  tests/unit/test__pandas_helpers.py
Labels: cla: yes, release blocking

#195 tests: avoid use of systest envvars in unit tests
  tests/unit/test_client.py
  tests/unit/test_magics.py
Labels: cla: yes, testing, type: process

#167 doc: update CHANGELOG for version 1.10.0
  CHANGELOG.md
Labels: automerge, cla: yes

#144 feat: add support for getting and setting table IAM policy
  google/cloud/bigquery/client.py
  google/cloud/bigquery/iam.py
  tests/system.py
  tests/unit/test_client.py
Labels: cla: yes

#163 fix: raise error if inserting rows with unknown fields
  google/cloud/bigquery/_helpers.py
  tests/unit/test__helpers.py
Labels: cla: yes

#197 tests: remove warning spew
  tests/unit/test__pandas_helpers.py
  tests/unit/test_client.py
  tests/unit/test_job.py
  tests/unit/test_magics.py
  tests/unit/test_table.py
Labels: automerge, cla: yes, testing, type: process
