Repository googleapis/python-bigquery, pull requests merged in 2020-10, with the labels that each got.

#276 test: update tests to support latest google-cloud-core
  tests/unit/test__http.py
Labels: api: bigquery, cla: yes

#283 feat: add constants for MONTH and YEAR time partitioning types
  google/cloud/bigquery/table.py
Labels: api: bigquery, cla: yes

#291 docs(samples): add create_table_clustered code snippet
  docs/usage/tables.rst
  samples/create_table_clustered.py
  samples/tests/test_create_table_clustered.py
Labels: cla: yes

#26 perf: remove redundant array deepcopy
  google/cloud/bigquery/_helpers.py
  tests/unit/test__helpers.py
Labels: cla: yes

#279 chore(python): skip reporting coverage for namespace package
  .coveragerc
  synth.metadata
Labels: api: bigquery, cla: yes, context: full

#308 fix: remove unnecessary dependency on libcst
  scripts/fixup_bigquery_v2_keywords.py
  setup.py
  synth.py
Labels: cla: yes

#309 docs: update snippets samples to support version 2.0
  samples/snippets/authorized_view_tutorial.py
  samples/snippets/authorized_view_tutorial_test.py
  samples/snippets/natality_tutorial.py
  samples/snippets/natality_tutorial_test.py
  samples/snippets/quickstart.py
  samples/snippets/requirements.txt
Labels: cla: yes

#310 chore: start tracking obsolete files
  .kokoro/presubmit/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  mypy.ini
  synth.metadata
Labels: automerge, cla: yes, context: partial

#307 fix: use version.py instead of pkg_resources.get_distribution
  google/cloud/bigquery/__init__.py
  google/cloud/bigquery/version.py
  setup.py
Labels: cla: yes

#314 deps: require pyarrow for pandas support
  docs/snippets.py
  google/cloud/bigquery/__init__.py
  google/cloud/bigquery/client.py
  google/cloud/bigquery/exceptions.py
  google/cloud/bigquery/table.py
  noxfile.py
  setup.py
  testing/constraints-3.6.txt
  tests/unit/test__pandas_helpers.py
  tests/unit/test_client.py
  tests/unit/test_job.py
  tests/unit/test_table.py
Labels: automerge, cla: yes

#299 feat: add to_api_repr method to TableListItem
  google/cloud/bigquery/table.py
  tests/unit/test_table.py
Labels: cla: yes

#286 docs: update clustering field docstrings
  google/cloud/bigquery/job.py
  google/cloud/bigquery/table.py
Labels: automerge, cla: yes

#110 fix: make TimePartitioning repr evaluable
  google/cloud/bigquery/table.py
  tests/unit/test_table.py
Labels: automerge, cla: yes

#280 perf: add size parameter for load table from dataframe and json methods
  google/cloud/bigquery/client.py
  tests/unit/test_client.py
Labels: api: bigquery, cla: yes

#326 feat: add to_api_repr method to Model
  google/cloud/bigquery/model.py
  tests/unit/model/test_model.py
Labels: cla: yes

#322 feat: allow client options to be set in magics context
  google/cloud/bigquery/magics/magics.py
  tests/unit/test_magics.py
Labels: cla: yes

#323 refactor: update Job classes to use common _properties pattern
  google/cloud/bigquery/job.py
  tests/unit/test_client.py
  tests/unit/test_job.py
Labels: cla: yes

#306 deps: add protobuf dependency
  setup.py
  testing/constraints-3.6.txt
Labels: automerge, cla: yes

#219 tests: split out snippets builds
  .kokoro/presubmit/presubmit.cfg
  .kokoro/presubmit/snippets-2.7.cfg
  .kokoro/presubmit/snippets-3.8.cfg
  noxfile.py
Labels: api: bigquery, automerge, cla: yes

#327 feat: add timeout paramter to load_table_from_file and it dependent methods
  google/cloud/bigquery/client.py
  tests/unit/test_client.py
Labels: cla: yes

#300 fix: broken create_job method
  google/cloud/bigquery/client.py
  tests/unit/test_client.py
Labels: cla: yes

#340 test: make `_AsyncJob` tests mock at a lower layer
  google/cloud/bigquery/client.py
  google/cloud/bigquery/job.py
  tests/unit/test_job.py
Labels: cla: yes

#344 docs: added document of QueryPlanEntry and QueryPlanEntryStep
  docs/reference.rst
  google/cloud/bigquery/job.py
Labels: cla: yes

#341 feat: add `reload` argument to `*Job.done()` functions
  google/cloud/bigquery/job.py
  tests/unit/test_job.py
  tests/unit/test_magics.py
Labels: automerge, cla: yes

#348 fix(dbapi): avoid running % format with no query parameters
  google/cloud/bigquery/dbapi/cursor.py
  tests/unit/test_dbapi_cursor.py
Labels: cla: yes
