Repository googleapis/python-bigquery, pull requests merged in 2020-06, with the labels that each got.

#119 docs: explain the limitation of IPython magic dict arguments
  google/cloud/bigquery/magics.py
Labels: cla: yes, type: docs

#121 feat(bigquery): expose start index parameter for query result
  google/cloud/bigquery/job.py
  tests/system.py
  tests/unit/test_job.py
Labels: cla: yes

#127 doc: update wording in rowiterator docstrings to reduce confusion
  google/cloud/bigquery/table.py
Labels: cla: yes, type: docs

#132 docs(bigquery): add client thread-safety documentation
  docs/index.rst
Labels: cla: yes

#133 chore: remove workarounds for BQ Storage issue with small result sets
  google/cloud/bigquery/dbapi/connection.py
  google/cloud/bigquery/dbapi/cursor.py
  google/cloud/bigquery/job.py
  google/cloud/bigquery/table.py
  tests/system.py
  tests/unit/test_dbapi_cursor.py
  tests/unit/test_job.py
  tests/unit/test_table.py
Labels: cla: yes, type: cleanup

#135 chore: restrict `rsa` version to <=4.0 for Python 2.7 compatibility
  setup.py
Labels: cla: yes, type: process

#139 docs(bigquery): fix the broken docs
  docs/conf.py
  google/cloud/bigquery/dataset.py
  synth.py
Labels: cla: yes

#128 fix: dry run queries with DB API cursor
  google/cloud/bigquery/dbapi/cursor.py
  tests/system.py
  tests/unit/test_dbapi_cursor.py
Labels: cla: yes

#153 docs(bigquery): consistent use of optional keyword
  google/cloud/bigquery/_helpers.py
  google/cloud/bigquery/_http.py
  google/cloud/bigquery/_pandas_helpers.py
  google/cloud/bigquery/client.py
  google/cloud/bigquery/dataset.py
  google/cloud/bigquery/job.py
  google/cloud/bigquery/magics.py
  google/cloud/bigquery/model.py
  google/cloud/bigquery/query.py
  google/cloud/bigquery/routine.py
  google/cloud/bigquery/schema.py
  google/cloud/bigquery/table.py
Labels: cla: yes
