Repository googleapis/python-bigquery, pull requests merged in 2020-05, with the labels that each got.

#90 chore: install google-cloud-testutils by package name
  noxfile.py
Labels: cla: yes, type: process

#71 feat(bigquery): add support of model for extract job
  google/cloud/bigquery/client.py
  google/cloud/bigquery/job.py
  google/cloud/bigquery/model.py
  tests/unit/test_client.py
  tests/unit/test_job.py
Labels: cla: yes

#98 docs(samples): deprecate client.dataset method
  docs/snippets.py
Labels: cla: yes

#103 chore: fix lint error in job.py module
  google/cloud/bigquery/job.py
Labels: cla: yes, type: process

#28 refactor(bigquery): update code samples of load table autodetect and truncate
  docs/snippets.py
  docs/usage/tables.rst
  samples/load_table_uri_autodetect_csv.py
  samples/load_table_uri_autodetect_json.py
  samples/load_table_uri_truncate_avro.py
  samples/load_table_uri_truncate_csv.py
  samples/load_table_uri_truncate_json.py
  samples/load_table_uri_truncate_orc.py
  samples/load_table_uri_truncate_parquet.py
  samples/tests/test_load_table_uri_autodetect_csv.py
  samples/tests/test_load_table_uri_autodetect_json.py
  samples/tests/test_load_table_uri_truncate_avro.py
  samples/tests/test_load_table_uri_truncate_csv.py
  samples/tests/test_load_table_uri_truncate_json.py
  samples/tests/test_load_table_uri_truncate_orc.py
  samples/tests/test_load_table_uri_truncate_parquet.py
Labels: cla: yes

#39 feat(bigquery): unit and system test for dataframe with int column with Nan values
  tests/system.py
  tests/unit/test_client.py
Labels: cla: yes

#101 chore: use google-cloud-testutils in noxfile
  noxfile.py
Labels: cla: yes

#91 feat: add HOUR support for time partitioning interval
  google/cloud/bigquery/table.py
  tests/unit/test_table.py
Labels: cla: yes

#93 feat: add a __hash__ implementation to AccessEntry
  google/cloud/bigquery/dataset.py
  tests/unit/test_dataset.py
Labels: cla: yes

#77 feat: add support for policy tags
  google/cloud/bigquery/schema.py
  tests/system.py
  tests/unit/test_schema.py
Labels: cla: yes

#111 docs(samples): deprecate client.dataset in samples
  docs/snippets.py
Labels: cla: yes, type: docs

#114 test(system): update tests to use DatasetReference
  tests/system.py
Labels: cla: yes
