Repository googleapis/python-bigquery, pull requests merged in 2022-05, with the labels that each got.

#1239 docs: updated variable typo in comment in code sample
  samples/undelete_table.py
Labels: api: bigquery, samples, size: xs

#1245 fix(deps): allow pyarrow v8
  setup.py
Labels: api: bigquery, size: xs

#1235 feat: add support for table clones
  docs/reference.rst
  google/cloud/bigquery/__init__.py
  google/cloud/bigquery/job/copy_.py
  google/cloud/bigquery/table.py
  samples/magics/requirements.txt
  tests/system/test_client.py
  tests/unit/test_table.py
Labels: api: bigquery, size: m

#1263 fix(deps): require protobuf>= 3.12.0, <4.0.0dev
  setup.py
Labels: api: bigquery, automerge, size: xs

#1266 fix(deps): require protobuf>= 3.12.0, <4.0.0dev on v2 branch
  setup.py
Labels: api: bigquery, size: xs
