Repository googleapis/python-bigquery, pull requests merged in 2022-06, with the labels that each got.

#1268 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: bigquery, size: s

#1269 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: bigquery, size: s

#1271 fix(deps): require protobuf<4.0.0 on v1 branch
  noxfile.py
  setup.py
Labels: api: bigquery, size: xs

#1277 feat: add destination_expiration_time property to copy job
  google/cloud/bigquery/job/copy_.py
  tests/system/test_client.py
  tests/unit/job/test_copy.py
Labels: api: bigquery, size: s

#1274 docs(samples): add table snapshot sample
  samples/snippets/conftest.py
  samples/snippets/create_table_snapshot.py
  samples/snippets/create_table_snapshot_test.py
Labels: api: bigquery, samples, size: m

#1123 doc: share design document for query retry logic
  docs/design/index.rst
  docs/design/query-retries.md
  docs/index.rst
Labels: api: bigquery, size: m
