Repository googleapis/python-bigquery, pull requests merged in 2022-03, with the labels that each got.

#1157 fix(deps): require google-api-core>=1.31.5, >=2.3.2
  setup.py
  testing/constraints-3.6.txt
Labels: api: bigquery

#1171 fix: update content-type header
  google/cloud/bigquery/client.py
Labels: api: bigquery

#1169 test: Move tests/unit/helpers to tests/unit/_helpers
  tests/unit/_helpers/__init__.py
  tests/unit/_helpers/test_from_json.py
Labels: api: bigquery, automerge

#1173 chore: update release script on v1 branch
  .kokoro/release.sh
  .kokoro/release/common.cfg
Labels: api: bigquery

#1166 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
  noxfile.py
  samples/update_dataset_access.py
  setup.py
  tests/unit/test__http.py
Labels: api: bigquery

#1027 docs: Add migration guide from version 2.x to 3.x
  UPGRADING.md
  docs/index.rst
Labels: api: bigquery, cla: yes

#1181 chore: add branch protection rules for v2
  .github/sync-repo-settings.yaml
Labels: api: bigquery

#1187 fix(deps): restore dependency on python-dateutil
  setup.py
Labels: api: bigquery

#1191 fix(deps): raise exception when pandas is installed but db-dtypes is not
  google/cloud/bigquery/_pandas_helpers.py
  google/cloud/bigquery/table.py
  tests/unit/test__pandas_helpers.py
  tests/unit/test_table.py
Labels: api: bigquery, automerge
