Repository googleapis/python-bigquery, pull requests merged in 2024-07, with the labels that each got.

#1971 chore: remove references to conda
  noxfile.py
Labels: api: bigquery, size: xs

#1972 deps: bump min version of google-api-core and google-cloud-core to 2.x
  setup.py
  testing/constraints-3.7.txt
Labels: api: bigquery, size: s

#1965 feat: use `bigquery-magics` package for the `%%bigquery` magic
  google/cloud/bigquery/__init__.py
  google/cloud/bigquery/magics/magics.py
  samples/magics/noxfile_config.py
  samples/magics/query.py
  samples/magics/query_params_scalars.py
  samples/magics/requirements.txt
  samples/notebooks/jupyter_tutorial_test.py
  samples/notebooks/requirements.txt
  setup.py
  testing/constraints-3.7.txt
  tests/system/test_magics.py
  tests/unit/test_magics.py
Labels: api: bigquery, size: l

#1975 chore: update templated files
  .flake8
  .github/.OwlBot.lock.yaml
  .github/auto-label.yaml
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/requirements.txt
  .kokoro/populate-secrets.sh
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/requirements.txt
  .kokoro/test-samples-against-head.sh
  .kokoro/test-samples-impl.sh
  .kokoro/test-samples.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .pre-commit-config.yaml
  .trampolinerc
  MANIFEST.in
  docs/conf.py
  owlbot.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
Labels: api: bigquery, size: l

#1976 fix: Allow protobuf 5.x; require protobuf >=3.20.2; proto-plus >=1.22.3
  setup.py
  testing/constraints-3.7.txt
Labels: api: bigquery, size: xs

#1978 docs: add short mode query sample & test
  samples/client_query_shortmode.py
  samples/tests/test_client_query_shortmode.py
Labels: api: bigquery, samples, size: m
