Repository googleapis/python-bigquery, pull requests merged in 2025-09, with the labels that each got.

#2280 fix: remove deepcopy while setting properties for _QueryResults
  google/cloud/bigquery/query.py
Labels: api: bigquery, size: xs

#2270 feat: add additional query stats
  google/cloud/bigquery/job/__init__.py
  google/cloud/bigquery/job/query.py
  tests/unit/job/test_query.py
  tests/unit/job/test_query_stats.py
Labels: api: bigquery, size: m

#2284 feat: microgen - adds config file
  scripts/microgenerator/config.yaml
Labels: api: bigquery, size: m

#2287 feat: microgen - adds _helpers.py.j2 template
  scripts/microgenerator/templates/_helpers.py.j2
Labels: api: bigquery, size: m

#2291 feat: migrate __init__.py file
  scripts/microgenerator/__init__.py
Labels: api: bigquery, size: u

#2303 docs: remove experimental annotations from GA features
  google/cloud/bigquery/external_config.py
Labels: api: bigquery, size: s

#2306 feat: microgen - add kokoro directory to support development
  .kokoro/build.sh
  .kokoro/continuous/common.cfg
  .kokoro/continuous/continuous.cfg
  .kokoro/continuous/prerelease-deps-3.13.cfg
  .kokoro/continuous/unit-tests-misc.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/linting-typing.cfg
  .kokoro/presubmit/prerelease-deps.cfg
  .kokoro/presubmit/snippets-3.13.cfg
  .kokoro/presubmit/snippets-3.9.cfg
  .kokoro/presubmit/system-3.13.cfg
  .kokoro/presubmit/system-3.9.cfg
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.10/common.cfg
  .kokoro/samples/python3.10/continuous.cfg
  .kokoro/samples/python3.10/periodic-head.cfg
  .kokoro/samples/python3.10/periodic.cfg
  .kokoro/samples/python3.10/presubmit.cfg
  .kokoro/samples/python3.11/common.cfg
  .kokoro/samples/python3.11/continuous.cfg
  .kokoro/samples/python3.11/periodic-head.cfg
  .kokoro/samples/python3.11/periodic.cfg
  .kokoro/samples/python3.11/presubmit.cfg
  .kokoro/samples/python3.12/common.cfg
  .kokoro/samples/python3.12/continuous.cfg
  .kokoro/samples/python3.12/periodic-head.cfg
  .kokoro/samples/python3.12/periodic.cfg
  .kokoro/samples/python3.12/presubmit.cfg
  .kokoro/samples/python3.13/common.cfg
  .kokoro/samples/python3.13/continuous.cfg
  .kokoro/samples/python3.13/periodic-head.cfg
  .kokoro/samples/python3.13/periodic.cfg
  .kokoro/samples/python3.13/presubmit.cfg
  .kokoro/samples/python3.9/common.cfg
  .kokoro/samples/python3.9/continuous.cfg
  .kokoro/samples/python3.9/periodic-head.cfg
  .kokoro/samples/python3.9/periodic.cfg
  .kokoro/samples/python3.9/presubmit.cfg
  .kokoro/test-samples-against-head.sh
  .kokoro/test-samples-impl.sh
  .kokoro/test-samples.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
Labels: api: bigquery, size: l

#2308 fix: remove ambiguous error codes from query retries
  google/cloud/bigquery/retry.py
Labels: api: bigquery, size: xs

#2294 feat: microgen - adds code generation logic
  scripts/microgenerator/generate.py
Labels: api: bigquery, size: m

#2295 feat: microgen - adds main execution and post processing
  scripts/microgenerator/generate.py
Labels: api: bigquery, size: m
